"""
Country configuration for localization.

Maps ISO 3166-1 alpha-2 country codes to jurisdiction and language settings.
"""

COUNTRY_CONFIG = {
    'AF': {'jurisdiction': 'Afghanistan', 'language': 'en'},
    'AL': {'jurisdiction': 'Albania', 'language': 'en'},
    'DZ': {'jurisdiction': 'Algeria', 'language': 'en'},
    'AO': {'jurisdiction': 'Angola', 'language': 'en'},
    'AR': {'jurisdiction': 'Argentina', 'language': 'es'},
    'AM': {'jurisdiction': 'Armenia', 'language': 'en'},
    'AU': {'jurisdiction': 'Australia', 'language': 'en'},
    'AT': {'jurisdiction': 'Austria', 'language': 'de'},
    'AZ': {'jurisdiction': 'Azerbaijan', 'language': 'en'},
    'BH': {'jurisdiction': 'Bahrain', 'language': 'en'},
    'BD': {'jurisdiction': 'Bangladesh', 'language': 'en'},
    'BY': {'jurisdiction': 'Belarus', 'language': 'en'},
    'BE': {'jurisdiction': 'Belgium', 'language': 'nl'},
    'BZ': {'jurisdiction': 'Belize', 'language': 'en'},
    'BJ': {'jurisdiction': 'Benin', 'language': 'en'},
    'BT': {'jurisdiction': 'Bhutan', 'language': 'en'},
    'BO': {'jurisdiction': 'Bolivia', 'language': 'es'},
    'BA': {'jurisdiction': 'Bosnia and Herzegovina', 'language': 'en'},
    'BW': {'jurisdiction': 'Botswana', 'language': 'en'},
    'BR': {'jurisdiction': 'Brazil', 'language': 'en'},
    'BG': {'jurisdiction': 'Bulgaria', 'language': 'en'},
    'KH': {'jurisdiction': 'Cambodia', 'language': 'en'},
    'CM': {'jurisdiction': 'Cameroon', 'language': 'en'},
    'CA': {'jurisdiction': 'Canada', 'language': 'en'},
    'CL': {'jurisdiction': 'Chile', 'language': 'es'},
    'CN': {'jurisdiction': 'China', 'language': 'en'},
    'CO': {'jurisdiction': 'Colombia', 'language': 'es'},
    'CR': {'jurisdiction': 'Costa Rica', 'language': 'es'},
    'HR': {'jurisdiction': 'Croatia', 'language': 'en'},
    'CU': {'jurisdiction': 'Cuba', 'language': 'es'},
    'CY': {'jurisdiction': 'Cyprus', 'language': 'en'},
    'CZ': {'jurisdiction': 'Czech Republic', 'language': 'en'},
    'DK': {'jurisdiction': 'Denmark', 'language': 'en'},
    'DO': {'jurisdiction': 'Dominican Republic', 'language': 'es'},
    'EC': {'jurisdiction': 'Ecuador', 'language': 'es'},
    'EG': {'jurisdiction': 'Egypt', 'language': 'en'},
    'SV': {'jurisdiction': 'El Salvador', 'language': 'es'},
    'EE': {'jurisdiction': 'Estonia', 'language': 'en'},
    'FI': {'jurisdiction': 'Finland', 'language': 'en'},
    'FR': {'jurisdiction': 'France', 'language': 'fr'},
    'GE': {'jurisdiction': 'Georgia', 'language': 'en'},
    'DE': {'jurisdiction': 'Germany', 'language': 'de'},
    'GH': {'jurisdiction': 'Ghana', 'language': 'en'},
    'GR': {'jurisdiction': 'Greece', 'language': 'en'},
    'GT': {'jurisdiction': 'Guatemala', 'language': 'es'},
    'HN': {'jurisdiction': 'Honduras', 'language': 'es'},
    'HU': {'jurisdiction': 'Hungary', 'language': 'en'},
    'IS': {'jurisdiction': 'Iceland', 'language': 'en'},
    'IN': {'jurisdiction': 'India', 'language': 'en'},
    'ID': {'jurisdiction': 'Indonesia', 'language': 'en'},
    'IR': {'jurisdiction': 'Iran', 'language': 'en'},
    'IQ': {'jurisdiction': 'Iraq', 'language': 'en'},
    'IE': {'jurisdiction': 'Ireland', 'language': 'en'},
    'IL': {'jurisdiction': 'Israel', 'language': 'en'},
    'IT': {'jurisdiction': 'Italy', 'language': 'it'},
    'JM': {'jurisdiction': 'Jamaica', 'language': 'en'},
    'JP': {'jurisdiction': 'Japan', 'language': 'en'},
    'JO': {'jurisdiction': 'Jordan', 'language': 'en'},
    'KZ': {'jurisdiction': 'Kazakhstan', 'language': 'en'},
    'KE': {'jurisdiction': 'Kenya', 'language': 'en'},
    'KR': {'jurisdiction': 'South Korea', 'language': 'en'},
    'KW': {'jurisdiction': 'Kuwait', 'language': 'en'},
    'KG': {'jurisdiction': 'Kyrgyzstan', 'language': 'en'},
    'LA': {'jurisdiction': 'Laos', 'language': 'en'},
    'LV': {'jurisdiction': 'Latvia', 'language': 'en'},
    'LB': {'jurisdiction': 'Lebanon', 'language': 'en'},
    'LY': {'jurisdiction': 'Libya', 'language': 'en'},
    'LT': {'jurisdiction': 'Lithuania', 'language': 'en'},
    'LU': {'jurisdiction': 'Luxembourg', 'language': 'en'},
    'MK': {'jurisdiction': 'North Macedonia', 'language': 'en'},
    'MG': {'jurisdiction': 'Madagascar', 'language': 'en'},
    'MW': {'jurisdiction': 'Malawi', 'language': 'en'},
    'MY': {'jurisdiction': 'Malaysia', 'language': 'en'},
    'MX': {'jurisdiction': 'Mexico', 'language': 'es'},
    'MN': {'jurisdiction': 'Mongolia', 'language': 'en'},
    'ME': {'jurisdiction': 'Montenegro', 'language': 'en'},
    'MA': {'jurisdiction': 'Morocco', 'language': 'en'},
    'MZ': {'jurisdiction': 'Mozambique', 'language': 'en'},
    'MM': {'jurisdiction': 'Myanmar', 'language': 'en'},
    'NA': {'jurisdiction': 'Namibia', 'language': 'en'},
    'NP': {'jurisdiction': 'Nepal', 'language': 'en'},
    'NL': {'jurisdiction': 'Netherlands', 'language': 'nl'},
    'NZ': {'jurisdiction': 'New Zealand', 'language': 'en'},
    'NI': {'jurisdiction': 'Nicaragua', 'language': 'es'},
    'NG': {'jurisdiction': 'Nigeria', 'language': 'en'},
    'NO': {'jurisdiction': 'Norway', 'language': 'en'},
    'OM': {'jurisdiction': 'Oman', 'language': 'en'},
    'PK': {'jurisdiction': 'Pakistan', 'language': 'en'},
    'PA': {'jurisdiction': 'Panama', 'language': 'es'},
    'PE': {'jurisdiction': 'Peru', 'language': 'es'},
    'PH': {'jurisdiction': 'Philippines', 'language': 'en'},
    'PL': {'jurisdiction': 'Poland', 'language': 'en'},
    'PT': {'jurisdiction': 'Portugal', 'language': 'pt'},
    'PR': {'jurisdiction': 'Puerto Rico', 'language': 'es'},
    'QA': {'jurisdiction': 'Qatar', 'language': 'en'},
    'RO': {'jurisdiction': 'Romania', 'language': 'ro'},
    'RU': {'jurisdiction': 'Russia', 'language': 'en'},
    'SA': {'jurisdiction': 'Saudi Arabia', 'language': 'en'},
    'SN': {'jurisdiction': 'Senegal', 'language': 'en'},
    'RS': {'jurisdiction': 'Serbia', 'language': 'en'},
    'SG': {'jurisdiction': 'Singapore', 'language': 'en'},
    'SK': {'jurisdiction': 'Slovakia', 'language': 'en'},
    'SI': {'jurisdiction': 'Slovenia', 'language': 'en'},
    'ZA': {'jurisdiction': 'South Africa', 'language': 'en'},
    'ES': {'jurisdiction': 'Spain', 'language': 'es'},
    'LK': {'jurisdiction': 'Sri Lanka', 'language': 'en'},
    'SE': {'jurisdiction': 'Sweden', 'language': 'en'},
    'CH': {'jurisdiction': 'Switzerland', 'language': 'en'},
    'TH': {'jurisdiction': 'Thailand', 'language': 'en'},
    'TN': {'jurisdiction': 'Tunisia', 'language': 'en'},
    'TR': {'jurisdiction': 'Turkey', 'language': 'en'},
    'UG': {'jurisdiction': 'Uganda', 'language': 'en'},
    'UA': {'jurisdiction': 'Ukraine', 'language': 'en'},
    'AE': {'jurisdiction': 'United Arab Emirates', 'language': 'en'},
    'GB': {'jurisdiction': 'United Kingdom', 'language': 'en'},
    'US': {'jurisdiction': 'United States', 'language': 'en'},
    'UY': {'jurisdiction': 'Uruguay', 'language': 'es'},
    'UZ': {'jurisdiction': 'Uzbekistan', 'language': 'en'},
    'VE': {'jurisdiction': 'Venezuela', 'language': 'es'},
    'VN': {'jurisdiction': 'Vietnam', 'language': 'en'},
    'YE': {'jurisdiction': 'Yemen', 'language': 'en'},
    'ZM': {'jurisdiction': 'Zambia', 'language': 'en'},
    'ZW': {'jurisdiction': 'Zimbabwe', 'language': 'en'},
}

# Default fallback for unsupported countries
DEFAULT_CONFIG = {'jurisdiction': 'Not supported yet', 'language': 'en'}

# Default for local development
LOCAL_DEV_CONFIG = {'jurisdiction': 'United Kingdom', 'language': 'en'}


def get_country_config(iso_code: str) -> dict:
    """Get configuration for a country by ISO code."""
    return COUNTRY_CONFIG.get(iso_code, DEFAULT_CONFIG)
